import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Providers } from "./providers";
import { Toaster } from "@/components/ui/sonner";
import AuthBootstrap from "@/components/providers/AuthBootstrap";
// @ts-ignore: side-effect import of CSS file without type declarations
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <AuthBootstrap/>
          {children}
          <Toaster 
  position="top-right" 
  richColors 
  theme="system" // or "light" / "system"
  duration={4000} 
/>
        </Providers>
        
      </body>
    </html>
  );
}
